# Generated by Django 4.2 on 2023-05-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyhistory',
            name='bank_name',
            field=models.CharField(choices=[('UAH', 'UAH'), ('USD', 'USD'), ('EUR', 'EUR'), ('BTCUSDT', 'BTC'), ('ETHUSDT', 'ETH')], default=None, max_length=16),
        ),
        migrations.AlterField(
            model_name='currencyhistory',
            name='code',
            field=models.CharField(choices=[('UAH', 'UAH'), ('USD', 'USD'), ('EUR', 'EUR'), ('BTCUSDT', 'BTC'), ('ETHUSDT', 'ETH')], default='UAH', max_length=16),
        ),
    ]
