# Generated by Django 4.2 on 2023-06-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_alter_currencyhistory_bank_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyhistory',
            name='bank_name',
            field=models.CharField(choices=[('UAH', 'UAH'), ('USD', 'USD'), ('EUR', 'EUR'), ('BTCUSDT', 'BTC'), ('ETHUSDT', 'ETH')], default='None', max_length=16),
        ),
    ]
